# Generated by Django 5.2.3 on 2025-10-07 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('goal', models.CharField(blank=True, max_length=100, null=True)),
                ('injuries', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DayRutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.TextField(blank=True, max_length=255, null=True)),
                ('muscle_group', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignatures', to='entidades.client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignatures', to='entidades.coach')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseRutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=45)),
                ('repetitions', models.CharField(max_length=255)),
                ('type_serie', models.CharField(choices=[('normal', 'Normal'), ('drop_set', 'Drop Set'), ('superset', 'Superset'), ('giant_set', 'Giant Set')], max_length=45)),
                ('dia_rutine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_routines', to='entidades.dayrutine')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_routines', to='entidades.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_reminder', models.DateTimeField()),
                ('sent', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('asignature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='entidades.asignature')),
            ],
        ),
        migrations.CreateModel(
            name='Rutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_week', models.PositiveBigIntegerField()),
                ('is_template', models.BooleanField(default=False)),
                ('time_creation', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='entidades.coach')),
            ],
        ),
        migrations.AddField(
            model_name='dayrutine',
            name='rutine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_routines', to='entidades.rutine'),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(max_length=45)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='entidades.reminder')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_used', models.CharField(blank=True, max_length=255, null=True)),
                ('repetitions_made', models.CharField(blank=True, max_length=255, null=True)),
                ('rm_value', models.CharField(blank=True, max_length=255, null=True)),
                ('rutine_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_registers', to='entidades.exerciserutine')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_registers', to='entidades.trainingsession')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='entidades.user'),
        ),
    ]
