# Generated by Django 5.2.3 on 2025-08-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='muscle_groups',
            new_name='muscle_group',
        ),
    ]
