# Generated by Django 5.2.3 on 2025-08-12 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
    ]
