# Generated by Django 5.2.3 on 2025-08-17 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0006_client_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignatures', to='entidades.client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignatures', to='entidades.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_reminder', models.DateTimeField()),
                ('sent', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('asignature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='entidades.asignature')),
            ],
        ),
        migrations.CreateModel(
            name='Rutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_week', models.PositiveBigIntegerField()),
                ('is_template', models.BooleanField(max_length=45)),
                ('time_creation', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='entidades.coach')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(max_length=45)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='entidades.reminder')),
            ],
        ),
    ]
