# Generated by Django 5.2.3 on 2025-08-17 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0007_asignature_reminder_rutine_trainingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayRutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.CharField(max_length=45)),
                ('rutine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_routines', to='entidades.rutine')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseRutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=45)),
                ('repetitions', models.CharField(max_length=255)),
                ('tipe_serie', models.CharField(choices=[('normal', 'Normal'), ('drop_set', 'Drop Set'), ('superset', 'Superset'), ('giant_set', 'Giant Set')], max_length=45)),
                ('dia_rutine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_routines', to='entidades.dayrutine')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_routines', to='entidades.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercises', models.ManyToManyField(related_name='muscle_groups', to='entidades.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_weight', models.CharField(blank=True, null=True, verbose_name=255)),
                ('weight_used', models.CharField(blank=True, max_length=255, null=True)),
                ('repetitions_made', models.CharField(blank=True, max_length=255, null=True)),
                ('rm_value', models.CharField(blank=True, max_length=255, null=True)),
                ('rutine_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_registers', to='entidades.exerciserutine')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_registers', to='entidades.trainingsession')),
            ],
        ),
    ]
