# Generated by Django 5.2.3 on 2025-08-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0008_dayrutine_equipement_exerciserutine_musclegroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='musclegroup',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_groups',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='entidades.musclegroup'),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='entidades.equipement'),
        ),
    ]
