# Generated by Django 5.2.3 on 2025-08-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0009_remove_equipement_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_group',
        ),
    ]
